### ISSUE TITLE
XCode14  unavailable with '@available  

### ISSUE THREAD

**Issue by Nilix5** [codemagic-ci-cd/codemagic-docs#1016]
I am currently trying to create my IOS app with codemagic and load it into the store. I am using Flutter 3.3.3 with Android studio. When building with codemagic I get the following message, I can't find @available in the source code.

**Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/builder/programs/flutter_3_3_3/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/ios/Classes/Types/UserScript.swift:12:5**

I can't find any solution on the internet

**Comment by K-Codemagic** [comment]
Hi, try to update the version in Podfile 
`platform :ios, '14.0'`

Reset pods using:
` cd ios && rm -rf Pods/ Podfile.lock && pod install --repo-update`

**Comment by K-Codemagic** [comment]
Hi, I am closing this, however for issues please open it on GitHub Discussions.
