### ISSUE TITLE
Pushing change to the repo from build fails

### ISSUE THREAD

**Issue by ivinskyi** [codemagic-ci-cd/codemagic-docs#1034]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/1033

<div type='discussions-op-text'>

<sup>Originally posted by **ivinskyi** October  8, 2022</sup>
I'm trying to push a change to the repository from build, follow the advice here https://docs.codemagic.io/troubleshooting/accessing-builder-machine-via-ssh/#making-configuration-changes and it fails. 
Note: I put this in a build itself, not executing the commands via SSH or VNC connection, I assumed it should work. 

I can successfully use a token, for example, to list all my repos. 
```
gh auth status
```
shows 
```
github.com
  ✓ Logged in to github.com as ivinskyi (GITHUB_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
```
I then run 
```
gh auth setup-git
```
to use github token credentials from `gh`.

Then,
```
git push
```
Fails with 
```
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/ivinskyi/my_repo/': The requested URL returned error: 403
```

I tried to repeat the same steps on my dev machine and pushing changes works from my laptop.</div>

**Comment by himesh-cm** [comment]
Duplicate #1033
Please refer to the above link, and let's use the discussion board for queries.
