### ISSUE TITLE
Documentation is full of inconsistencies

### ISSUE THREAD

**Issue by enigmathix** [codemagic-ci-cd/codemagic-docs#1101]
**Describe the documentation update you'd like to see**
Look at https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/
It starts by giving a template for a yaml file in github.
At the end, it shows what the final yaml should look like.
Compare the two: they're completely different!
The first one talks about environment variables like APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY with little or no explanation on how to set them
The second one only shows setting up BUNDLE_ID and APP_ID (which btw has a different name in the other file!). The ios_signing entry is very simple, no mention of any variable to set.

So which is it? The doc goes through many steps to upload certificates and provisions and API key. You'd think with this there shouldn't be much to do in the yaml file, since everything is already on the site. So why does the template talk about setting those variables all over again?

**Additional context**
Add any other context or screenshots about the change request here.

**Getting support**
Support for customers who haven't enabled billing is available in the [Discussions](https://github.com/codemagic-ci-cd/codemagic-docs/discussions) section of this repository. 

If you have enabled billing in Codemagic, you can contact the support team directly using the in-app chat widget.

**Comment by todah-zg** [comment]
Hi @enigmathix,

Thank you for pointing this out. We are continuously updating our service with new features and trying to simplify CI/CD for you so some of the sample projects go out of sync with the latest features. We are aware of the fact and are working on remedying the fact. In fact, if you switch the sample projects repository branch from `main` to `rewrite`, you can track our progress in real time :-D.

The particular sample project you were looking for is [here](https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/rewrite/ios/ios-native-quick-start) and is waiting for approval.

To avoid any confusion and as a help to others - Codemagic [documentation site](https://docs.codemagic.io/) has precedence over sample projects in case they differ.

And yes, with the latest updates, iOS codesigning really is very simple in `codemagic.yaml` if you follow the new guides. That being said, the 'old' way still present in the sample project is still valid and working.

Again, thank you for pointing this out and please have some more patience while we update our sample projects.
