### ISSUE TITLE
Tutorial video for iOS code signing is outdated

### ISSUE THREAD

**Issue by rickgladwin** [codemagic-ci-cd/codemagic-docs#1103]
On this page
https://docs.codemagic.io/flutter-code-signing/ios-code-signing/

There is a link to a YouTube walkthrough for setting up code signing:
https://www.youtube.com/watch?v=aBDx6BKFXIA

The UI version for codemagic shown in the video (and the steps in the tutorial) do not match the current UI.

Certificates are currently set up under Teams > Personal Account > Account Settings > Integrations

**Comment by kevin-suhajda** [comment]
@codemagic-mohammed - please remove this video due to UI changes.
