### ISSUE TITLE
YAML configuration missing workflows

### ISSUE THREAD

**Issue by oscarshaitan** [codemagic-ci-cd/codemagic-docs#1141]
**Describe the documentation update you'd like to see**
I have 6 Workflows 
<img width="310" alt="Screen Shot 2022-11-07 at 16 48 11" src="https://user-images.githubusercontent.com/9093952/200367119-aaf1a2cf-fdc3-42cf-8f7a-cf8ecae07644.png">

But when I open the Yaml configuration I can only see the first 2.

**Additional context**
Also I spot that the first Flow name is
<img width="196" alt="Screen Shot 2022-11-07 at 16 51 36" src="https://user-images.githubusercontent.com/9093952/200367894-dcb3f2bb-b3c2-4a8c-95d6-f0b4aec02df1.png">
But the second 
<img width="213" alt="Screen Shot 2022-11-07 at 16 51 53" src="https://user-images.githubusercontent.com/9093952/200367937-87b04e32-5bbc-4c8a-a589-098678d9e235.png">

**Comment by icarusdust** [comment]
Hi @oscarshaitan as you also contacted via private chat, I could check the general settings. Please note that as you are checking the wrong app, you see only two workflows. You have two applications, one is Symterra-Mobile and the other one is Symterra-WebApp. Symterra-Mobile has all these 6 workflows but you are checking Symterra-WebApp application.

**Comment by nevercode-kevin** [comment]
Not a documentation issue. 

Community support is available [here](https://github.com/codemagic-ci-cd/codemagic-docs/discussions).
