### ISSUE TITLE
iOS code signing - document unable to create an authenticated sessions, error code=-22020

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#129]
Quite a common issue for code signing looks like:

altool[xxx:xxx] *** Error: Unable to validate archive '/Users/builder/ipas/xxx'.
altool[xxx:xxx] *** Error: code -22020 (Unable to validate your application. We are unable to create an authentication session.)

Problem seems more related to the connection with their apple account. User should have to set App Store Connect with an App Specific Password instead of their usual Apple password.

To do so, they should go to your apple id page, down to Security, and then App Specific Password > Generate a password

https://stackoverflow.com/questions/60718061/unable-to-create-an-authentication-session-on-codemagic-when-code-signing-on-ios

**Comment by rimanteval** [comment]
@rrrents We should add this to common issues.

**Comment by martinjeret** [comment]
It is currently in ios code signing section for common mistakes, but does
not include error code example

**Comment by priitlatt** [comment]
This error has nothing to do with code signing, and as such the issue description is misleading. It is about publishing to App Store Connect.

**Comment by VeArnold** [comment]
created PR: https://github.com/codemagic-ci-cd/codemagic-docs/pull/172

**Comment by VeArnold** [comment]
added with PR: https://github.com/codemagic-ci-cd/codemagic-docs/pull/172
