### ISSUE TITLE
AWS CodeCommit: Not able to clone repository

### ISSUE THREAD

**Issue by dzero1** [codemagic-ci-cd/codemagic-docs#1426]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/1424

<div type='discussions-op-text'>

<sup>Originally posted by **blattr** February 21, 2023</sup>
Hello everyone,

the last successful build of my (business) application was 4 days ago (id=63ef6bf5b44082171441493c). Since then, nothing changed in buildspec.yaml, any integration or credentials (on any side). For an unknown reason, I am not able to clone my repository on AWS CodeCommit anymore. The last failed build was just 30 minutes ago (id=63f4b9efc698fb64afb8ec19). I am connecting to AWS CodeCommit using HTTPs (username/password).

This is the error message (removed personal information):

_== Cloning from feature branch 'master' ==
\> /usr/bin/git clone -b master --depth 50 https://codemagic-at-123@git-codecommit.eu-central-1.amazonaws.com/v1/repos/abc /Users/builder/clone --progress
Cloning into '/Users/builder/clone'...
fatal: unable to access 'https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/abc/': The requested URL returned error: 403_

I also have a personal account with exact the same setup - it stopped working as well. If needed, I can provide the build ids as well of course.</div>

**Comment by kevin-suhajda** [comment]
Resolved in https://github.com/orgs/codemagic-ci-cd/discussions/1424
