### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by trobanga** [codemagic-ci-cd/codemagic-docs#1718]
Just want to let you know that in this section https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#build-versioning
is a a dead link.

1. Go to [this guide](https://docs.codemagic.io/knowledge-base/google-services-authentication) and complete the steps in the Google Play section.

**Comment by rafeysup93** [comment]
Hi @trobanga!

Thank you for bringing this to our attention. The document has been updated.
