### ISSUE TITLE
edit build versioning page to include PROJECT_BUILD_NUMBER variable

### ISSUE THREAD

**Issue by VeArnold** [codemagic-ci-cd/codemagic-docs#173]
we added the variable PROJECT_BUILD_NUMBER to keep track of builds across all workflows, will probably be nice to implement it in some way under our versioning documentation as well

**Comment by helinanever** [comment]
This has been documented in https://docs.codemagic.io/configuration/build-versioning/#build-versioning-from-codemagic-environment-variables
