### ISSUE TITLE
Updating codemagic-docs/content/publishing/publishing-to-google-play.md 

### ISSUE THREAD

**Issue by jimmytwilson** [codemagic-ci-cd/codemagic-docs#174]
Hi there,

I was recently following your tutorials about deployment to the Google Play store.
I noticed that in the section "Setting up a service account in Google Play Console" in the codemagic-docs/content/publishing/publishing-to-google-play.md tutorial, the Google Play Console have updated their process.

From step 4 is different. I have attached photos below to show the process now. They no longer have the "Role dropdown".

<img width="1135" alt="Screen Shot 2020-09-11 at 9 45 32 AM" src="https://user-images.githubusercontent.com/60309775/92833192-8b7cf680-f413-11ea-8895-119552902f76.png">

Instead, this can be found in step 2 after completing the details.

<img width="1137" alt="Screen Shot 2020-09-11 at 9 46 43 AM" src="https://user-images.githubusercontent.com/60309775/92833349-b6674a80-f413-11ea-852d-c5a18623fc43.png">

It then takes you to an optional 3rd step of granting users access to this service account.

<img width="739" alt="Screen Shot 2020-09-11 at 9 48 38 AM" src="https://user-images.githubusercontent.com/60309775/92833593-fb8b7c80-f413-11ea-81de-346bff1195a9.png">

After which you can download the json file.

I am quite new to the GitHub contribution world, but if you would like, I could try to update and make a pull request on your repo to include a new updated tutorial?

Thank you!
Jimmy Wilson

**Comment by helinanever** [comment]
HI @jimmytwilson , your contribution would be very much welcome!

**Comment by helinanever** [comment]
This section is updated in the restructured documentation.
