### ISSUE TITLE
add example for uploading .dsym to firebase crashlytics

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#178]
problem: customers have had issues with uploading deobfuscation symbols to Firebase Crashlytics

here is an example that @VeArnold and user came up with that worked according to user: 

```
echo "Find build artifacts"
dsymPath=$(find ~/build.xcarchive -name "*.dSYM.zip" | head -1)
if [[ -z ${dsymPath} ]]
then
  echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
else
  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
  ls -d -- ios/Pods/*
  $FCI_BUILD_DIR/ios/Pods/Crashlytics/iOS/Crashlytics.framework/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
fi
```

**Comment by KSLiquid** [comment]
@martinjeret thanks for your script! It did not work directly for me so I modified it.  Here is my updated version which does not only take the Runner.dsym.zip but all the other dsym files as well.

`
  echo "List all dSYM files artifacts"
  find . -name "*.dSYM*"

  dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
  echo $dSymZipPath

  dSymPath="$(dirname "${dSymZipPath}")"
  ls $dSymPath

  repoPathToIosFolder="<<path-to-ios-folder-in-my-repo>>"

  googleServicesPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Runner/GoogleService-Info.plist"
  ls $googleServicesPath
 
  crashlyticsScriptPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Pods/FirebaseCrashlytics/upload-symbols"
  ls $crashlyticsScriptPath

  echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
  $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath

`

**Comment by danielFloat** [comment]
> @martinjeret thanks for your script! It did not work directly for me so I modified it. Here is my updated version which does not only take the Runner.dsym.zip but all the other dsym files as well.
> 
> ```shell
>   echo "List all dSYM files artifacts"
>   find . -name "*.dSYM*"
> 
>   dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
>   echo $dSymZipPath
> 
>   dSymPath="$(dirname "${dSymZipPath}")"
>   ls $dSymPath
> 
>   repoPathToIosFolder="<<path-to-ios-folder-in-my-repo>>"
> 
>   googleServicesPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Runner/GoogleService-Info.plist"
>   ls $googleServicesPath
>  
>   crashlyticsScriptPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Pods/FirebaseCrashlytics/upload-symbols"
>   ls $crashlyticsScriptPath
> 
>   echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
>   $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath
> ```

Should I use this script on the "Post-Build script" on codemagic? Or is it in a different step?

Thank you for sharing this!

**Comment by KSLiquid** [comment]
> > @martinjeret thanks for your script! It did not work directly for me so I modified it. Here is my updated version which does not only take the Runner.dsym.zip but all the other dsym files as well.
> > ```shell
> >   echo "List all dSYM files artifacts"
> >   find . -name "*.dSYM*"
> > 
> >   dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
> >   echo $dSymZipPath
> > 
> >   dSymPath="$(dirname "${dSymZipPath}")"
> >   ls $dSymPath
> > 
> >   repoPathToIosFolder="<<path-to-ios-folder-in-my-repo>>"
> > 
> >   googleServicesPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Runner/GoogleService-Info.plist"
> >   ls $googleServicesPath
> >  
> >   crashlyticsScriptPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Pods/FirebaseCrashlytics/upload-symbols"
> >   ls $crashlyticsScriptPath
> > 
> >   echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
> >   $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath
> > ```
> 
> Should I use this script on the "Post-Build script" on codemagic? Or is it in a different step?
> 
> Thank you for sharing this!

No problem!
You should use it in the post-publish -script (the very last thing that happens)

**Comment by helinanever** [comment]
This issue has been addressed: https://docs.codemagic.io/knowledge-base/firebase-crashlytics-dsym-uploading/

**Comment by nguyenthanhphap1413** [comment]
> https://docs.codemagic.io/knowledge-base/firebase-crashlytics-dsym-uploading/

echo "Find build artifacts"
dsymPath=$(find ~/build.xcarchive -name "*.dSYM.zip" | head -1)
if [[ -z ${dsymPath} ]]
then
  echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
else
  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
  ls -d -- ios/Pods/*
  $FCI_BUILD_DIR/ios/Pods/Crashlytics/iOS/Crashlytics.framework/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
fi
i tried to follow the documentation but it uploaded incompletely. It just uploaded gprc. 
<img width="712" alt="Screen Shot 2022-09-24 at 21 36 31" src="https://user-images.githubusercontent.com/48199071/192103884-3ab0a644-6915-45ef-8dc9-cecd89ae114b.png">

**Comment by romatroskin** [comment]
> 

not working solution, seems like we need to specify path to the Runner.app.dSYM.zip instead of find

**Comment by VeArnold** [comment]
@romatroskin Hi!

I can not test right now, but based on the comments here, there might be some inconsistencies in how the files are generated for different projects. If I remember clearly, then this original script was Flutter-specific. I think there can also be inconsistencies between whether you have to search for `.dSYM` or `.dSYM.zip`. 

The potential issue most likely has risen from the fact that it finds some not all-inclusive `*.dSYM.zip` first, which might not contain everything necessary. I would say that in this case, the solution in the previous comments by @FlagshipApps might do the trick in just getting the directory. I think removing the `head -1` would most likely make the input invalid, or cause some duplicates.

In any case, best to make sure by actually looking at what files and where are generated, and then creating the script based on that. Happy to help out, if needed. There's also an example in Firebase docs, which might help out:
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios#manually-upload-dsyms
