### ISSUE TITLE
Unable to Download app-release.apk build from Phone

### ISSUE THREAD

**Issue by Aditya-QSS** [codemagic-ci-cd/codemagic-docs#2069]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2067

<div type='discussions-op-text'>

<sup>Originally posted by **Aditya-QSS** September 22, 2023</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I have triggered the build from Codemagic and I am able to download that build from my system but when I try to download it using my phone it shows Downloading... Download pending...

### Expected results

It should be downloadable from both the Phone and the System.

### Actual results

It is only getting downloaded from system not from phone.

### Build id (optional)

_No response_</div>

**Comment by kevin-suhajda** [comment]
Not an issue with documentation. Please continue in Discussions.
