### ISSUE TITLE
Google Play console screenshots are outtdated

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#2279]
**Describe the documentation update you'd like to see**
[Google Play ](https://docs.codemagic.io/flutter-publishing/publishing-to-google-play/) step 9 has outtdated screenshot since Play Store console has been updated. 

**Additional context**
I was preparing to do a demo of how to get started with Codemagic and using outdated screenshots is not a good idea.

**Comment by himesh-cm** [comment]
Here is the PR - https://github.com/codemagic-ci-cd/codemagic-docs/pull/2315

**Comment by himesh-cm** [comment]
This was merged
