### ISSUE TITLE
macOS M2 machine type is missing on machine type page

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#2318]
**Describe the documentation update you'd like to see**
Customers can use M2 machines if they buy an annual plan, but the machine type page does not show this

**Additional context**
Taha mentioned this when trying to figure out which machine types Codemagic supports. He wrote build machine type in search bar and landed on the build machine type page instead of macOS machine specs page where M2 is present.

**Comment by icarusdust** [comment]
I’d suggest removing the machine type page as machine specs pages have all the necessary information instead of updating the outdated and missing information on the machine type page.

**Comment by icarusdust** [comment]
Nah, let's keep it but redirect to the specs page.

**Comment by icarusdust** [comment]
PR #2471
