### ISSUE TITLE
iOS code signing prerequisite may be incorrect

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#2332]
**Describe the documentation update you'd like to see**
iOS code signing page https://docs.codemagic.io/flutter-code-signing/ios-code-signing/ has a prerequisite for provisioning profile and signing certificate. This is actually not a pre-requisite because I can use the Codemagic App Store connect integration to generate both of these. 

**Additional context**
I was preparing for a talk about CI/CD and iOS code signing and wanted to show off our wonderful docs. I would prefer to do so without telling on stage by the way this part of the docs is not entirely true, because you can just generate an App Store Connect API key for Codemagic with just the Apple Developer Program license.

**Comment by icarusdust** [comment]
PR #2470
