### ISSUE TITLE
URL Not Found, Moved repo from Org to Personal

### ISSUE THREAD

**Issue by ozayr** [codemagic-ci-cd/codemagic-docs#2362]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2361

<div type='discussions-op-text'>

<sup>Originally posted by **ozayr** February  6, 2024</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

transfer repo from Org to personal

### Expected results

Code magic correctly picks up change and updates the repo URL. I had moved this repo from personal to the org and the update url worked perfectly now when moving back its not updating

### Actual results

`Cannot update repository https://api.github.com/repos/Organisation/repositoryName
Repository was not found`

 however when I click the link below the app name on the app settings page it takes me to the correct repo ie the repo in my personal account

### Build id (optional)

_No response_</div>

**Comment by icarusdust** [comment]
Hi @ozayr, I replied to your query in the Discussions channel: https://github.com/orgs/codemagic-ci-cd/discussions/2361
