### ISSUE TITLE
Some generic documentation pages are not available in workflow editor view

### ISSUE THREAD

**Issue by helinanever** [codemagic-ci-cd/codemagic-docs#2412]
Some generic docs are available in the left menu only for yaml but not for Flutter Workflow Editor. For example, Build dashboards are only available in yaml docs https://docs.codemagic.io/yaml-publishing/build-dashboards/, the same goes for https://docs.codemagic.io/yaml-notification/github-checks/. 

Expected result:
Generic pages should be available in the menu regardless of the yaml / workflow editor switch status.

**Comment by dtrdic** [comment]
https://github.com/codemagic-ci-cd/codemagic-docs/pull/2468
