### ISSUE TITLE
Using a custom key for "Accessing private dependencies and Git submodules" does not work

### ISSUE THREAD

**Issue by brianbhsu** [codemagic-ci-cd/codemagic-docs#242]
After following the steps for using a custom key in order to access private git dependencies:

```
#!/usr/bin/env sh
echo "${CUSTOM_KEY_NAME}" > /tmp/ssh_key
chmod 600 /tmp/ssh_key
eval `ssh-agent -s`
ssh-add /tmp/ssh_key
```

This still causes the build to fail during the "Install Dependencies" step. The key is added successfully to the ssh-agent, but during the "Install Dependencies" step, it seems to be using a different shell session and does not have access to the ssh-agent and thus ssh key added in the Post-Clone script.

I tested this by trying to clone the private git repository in the Post-Clone script, which worked. But I'm unable to run code during the "Install Dependencies" step to debug further.

The only work around is to set the raw private key in an environment variable ending in _SSH_KEY, without base64 encoding it. This does the trick, but it's not ideal.

It should also be added in the docs that if you want to use the features of having environment variables ending with _SSH_KEY being automatically added to the ssh-agent throughout the entire build, they can't be base64 encoded.

**Comment by helinanever** [comment]
Both the logic of using SSH keys in Codemagic and the [docs](https://docs.codemagic.io/configuration/access-private-git-submodules/) have been updated, closing this issue as fixed now.
