### ISSUE TITLE
Documentation for webhook need update

### ISSUE THREAD

**Issue by renuvkelkar** [codemagic-ci-cd/codemagic-docs#2467]
Codemagic document for webhook https://docs.codemagic.io/flutter-running-builds/starting-builds-automatically/ mentioned 
"Codemagic automatically adds webhooks to the repositories added via GitHub app or from GitHub, GitLab or Bitbucket via the OAuth integration after you have enabled any of the triggers in this section. " but for me I have just integrate my github repo to codemagic and it shows me following result.
<img width="1287" alt="Screenshot 2024-04-12 at 14 43 51" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/32317593/bb336ac0-7772-461b-8e5d-90ee07ad00a1">
<img width="1287" alt="Screenshot 2024-04-12 at 14 44 12" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/32317593/79837b7d-0ba9-4852-ac00-3e2612955f85">

and I haven't added any trigger yet. so that means Webhook is integrated automatically when you integrate your GitHub or any other repository to codemagic

**Comment by icarusdust** [comment]
Could you please try it again, it works as explained in the docs for me.

**Comment by icarusdust** [comment]
@renuvkelkar as it behaves the same way as the documentation explains, I am closing this issue. Please feel free to re-open it if you have questions.
