### ISSUE TITLE
[RESOLVED] Network disruption🚨

### ISSUE THREAD

**Issue by matmicro** [codemagic-ci-cd/codemagic-docs#2605]
Still facing network issue, like :

      > Could not resolve org.ow2.asm:asm-analysis:9.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.pom'.
               > Read timed out
               
Then build fails.

Example with build ID 6677254c8d9f918904ee88ea

**Comment by himesh-cm** [comment]
Hey @matmicro,
Both above resources when I try to download them directly from the browser show a 404 error, could you please check once if the URLs are correct?

**Comment by himesh-cm** [comment]
Hey @matmicro,
Apologies for missing the thread. If you are still having issues, please bring them up in the GitHub discussion here.
https://github.com/orgs/codemagic-ci-cd/discussions/categories/q-a?discussions
