### ISSUE TITLE
using multiple ssh keys to fetch private dependencies

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#264]
If person uses 1 SSH key to get private git submodules for example then everything works as expected, but when multiple keys are used then they get added to the SSH agent, but for git operations. In this particular case that I had and we have had before. 

Flutter pub get uses the first key that was added to the agent and therefore will fail the build with the error that no such repository exists. 

Possible solutions include swapping the order in which the keys get added to SSH agent, but I would like to investigate it a bit and update docs. One workaround is potentially explicitly add the key to use before the flutter pub get command. 

```
         echo "${DART_SCHEMA_VALIDATION_SSH_KEY}" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        eval `ssh-agent -s`
        ssh-add /tmp/ssh_key
```

**Comment by nguyendacthienngan** [comment]
I also have this issues when I have multiple keys, thanks for your recommended solution

**Comment by icarusdust** [comment]
Adding multiple SSH keys has been added to the docs and it can be found [here](https://docs.codemagic.io/configuration/access-private-git-submodules/#using-multiple-ssh-keys)
