### ISSUE TITLE
Skip publishing to App Store Connect: no IPAs or PKGs found

### ISSUE THREAD

**Issue by zdary** [codemagic-ci-cd/codemagic-docs#2641]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2640

<div type='discussions-op-text'>

<sup>Originally posted by **zdary** July 19, 2024</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

Publishing step doesn't see generated ipa file.
With searching I've changed the definition to a full path with no luck
```
    artifacts:
      - $CM_BUILD_DIR/ios/App/build/ios/ipa/*.ipa
```
       
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/d3f7df98-db2b-4e61-b4e3-76a389e688da">

### Expected results

ipa would be detected

### Actual results

Skip publishing to App Store Connect: no IPAs or PKGs found

### Build id (optional)

669a58506176f48f5349256b</div>

**Comment by icarusdust** [comment]
Hi @zdary, I will go ahead and close this issue as you already opened it in the Discussions channel. Our team will check it and get back to you.
