### ISSUE TITLE
Extract duplicate `Creating the App Store Connect API key` sections to common code

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/codemagic-docs#268]
Searching `Creating the App Store Connect API key`, you'll see we have duplicated in the following places:
 * `signing-ios.md`
 * `ios-code-signing.md`
 * `build-versioning.md`
 
It's a useful section to drop in docs, but as we all know as developers, don't repeat yourself.
 
Let's extract this duplication into some sort of common code.

**Comment by nevercode-kevin** [comment]
Use the partials functionality to implement.

1. Create a folder called 'partials' in the content folder e.g. content/partials.
2. Create a markdown document in the partials folder with structure like this:

```
---
---
# Your title here

Your text here
```

3. Include the partial in and existing markdown document using the following syntax:

```
{{< include "/partials/filename.md" >}}
```
