### ISSUE TITLE
p8 file Invalid Api Key

### ISSUE THREAD

**Issue by rakeshadvani1000** [codemagic-ci-cd/codemagic-docs#2686]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2682

<div type='discussions-op-text'>

<sup>Originally posted by **rakeshadvani1000** August 14, 2024</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

1. In Team Settings > Integrations, click "Connect" for Developer Portal
2. I added Issuer ID, Key ID, Name and uploaded the P8 key file itself.
3. Every time, I upload it says "Invalid API Key". I checked the file and it has no spaces and it is direct download from Apple connect.

### Expected results

P8 file should get uploaded and integration should get completed.

### Actual results

Getting error - "Invalid API Key".

### Build id (optional)

_No response_</div>

**Comment by icarusdust** [comment]
As it is a support query, I will go ahead and close it here, the team will get back to you.
