### ISSUE TITLE
Vite build with sourcemaps

### ISSUE THREAD

**Issue by stylecramper** [codemagic-ci-cd/codemagic-docs#2770]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2765

<div type='discussions-op-text'>

<sup>Originally posted by **stylecramper** October  4, 2024</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Ionic/Capacitor

### Steps to reproduce

Our codemagic.yaml includes a script that uses vite to build artifacts using the command:
`vite build --sourcemap true`
If I run this command locally, the JS files and their associated sourcemap files are built into the ./dist/assets directory.

### Expected results

I expect the Codemagic build to do the same thing I'm seeing locally: build the JS files with their associated sourcemap files.

### Actual results

When the codemagic script runs the same command, I can see in the build overview that only the JS files - and not the sourcemap files - are built.

### Build id (optional)

66ff15f0704a7c9066add214</div>

**Comment by icarusdust** [comment]
Hi @stylecramper, as it is a discussion topic, I will close the issue here and the team will get back to you asap.  On a different note, I see that your team has access to the direct chat widget in the UI to get in touch with the support team, please use it next time for quicker support.

**Comment by stylecramper** [comment]
Many thanks @icarusdust !
