### ISSUE TITLE
iOS build taking infinite time to build - Previously it was working fine with the same yaml configuration.

### ISSUE THREAD

**Issue by yasirali133314** [codemagic-ci-cd/codemagic-docs#2794]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/2793

<div type='discussions-op-text'>

<sup>Originally posted by **yasirali133314** October 22, 2024</sup>
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Here is my codemagic iOS workflow.

  ios-workflow:
    name: IOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic Store Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.myApp
      vars:
        APP_STORE_APPLE_ID: my_apple_id_here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - yasirali8889905@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

### Expected results

It should submit build to the testflight.

### Actual results

Infinite loading on building IPA

### Build id (optional)

_No response_</div>

**Comment by icarusdust** [comment]
Hi @yasirali133314, as you already opened a support case in the link you provided, I will go ahead and close the issue here.
