### ISSUE TITLE
How to change Flutter produced binary names for Android and iOS

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#292]
Customers have been asking about how the resulting .apk from flutter build apk is named and how to rename it. 

Similar for iOS

**Comment by icarusdust** [comment]
For Android, configuring build.gradle with something like this should do it:

defaultConfig {
   ...
   archiveBaseName = "SomeApp-" + versionName + "-" + versionCode
   ...
} 

For iOS, changing <key>CFBundleName</key> string values and for iOS flavors, configuring app display name with <key>CFBundleDisplayName</key> should do it. However, should it be included in the docs ?
