### ISSUE TITLE
--build-number=$(yq e .version pubspec.yaml) this is not working as expected

### ISSUE THREAD

**Issue by uc-dve** [codemagic-ci-cd/codemagic-docs#350]
I am using it to get build-number for android and ios builds but it is giving me the following error.
And there is no documentation in the official doc on how to use it.

![image](https://user-images.githubusercontent.com/28289763/118765792-31350f00-b899-11eb-8b35-b815ce561d9e.png)

**Comment by craastad** [comment]
Hi @uc-dve. We recently merged https://github.com/codemagic-ci-cd/codemagic-docs/pull/360 to remove the misleading information of populating Flutter build argument with values of pubspec. Please join our [slack community](https://join.slack.com/t/codemagicio/shared_invite/zt-pt7dolhc-5Ltsqfg7EfPPhMUPMDA0EA) for support related questions.
