### ISSUE TITLE
Ios app not publishing to test flight and app store

### ISSUE THREAD

**Issue by uc-dve** [codemagic-ci-cd/codemagic-docs#353]
I have done all setups for publishing to app store connect, the app is uploaded to test flight, it is not distributed on test flight and app store.
I also got the app on email.

![image](https://user-images.githubusercontent.com/28289763/118779397-9e9c6c00-b8a8-11eb-8002-5d7f6ade87da.png)

![image](https://user-images.githubusercontent.com/28289763/118779203-7280eb00-b8a8-11eb-85e1-5d699b54c847.png)

Issue =>  it does not submitted for test flight testers, maybe it is not supported, but it is also not submitted to app store for review.
![image](https://user-images.githubusercontent.com/28289763/118780760-00110a80-b8aa-11eb-94b6-564438042546.png)

**Comment by helinanever** [comment]
@uc-dve Submitting the app to testers on TestFight is something we are currently working on and expect it to be available soon.

**Comment by uc-dve** [comment]
> @uc-dve Submitting the app to testers on TestFight is something we are currently working on and expect it to be available soon.

yeah! that's right no issue.
what about AppStore, how it works with submitting App to the app store review and release. 
Is it working or I have to submit it manually.

**Comment by craastad** [comment]
Closing this request for the same reason as https://github.com/codemagic-ci-cd/codemagic-docs/issues/354. Please file a Github issue only for proposed improvements to Codemagic docs.
