### ISSUE TITLE
ios app not installing which is provided through email.

### ISSUE THREAD

**Issue by uc-dve** [codemagic-ci-cd/codemagic-docs#354]
It is saying unable to install "AppName". this app cannot be installed because its integrity could not be verified.
below is the issue screenshot

![IMG_0186](https://user-images.githubusercontent.com/28289763/118781406-aa892d80-b8aa-11eb-943d-13945272e815.PNG)

I have got it in email
![image](https://user-images.githubusercontent.com/28289763/118781509-c260b180-b8aa-11eb-841c-6d97abbd2b89.png)

**Comment by craastad** [comment]
Hi @uc-dve this seems more like a support request than a proposed update to the Codemagic Documentation. If you can reformulate this as a proposed update to the docs I would be happy to reconsider it.

Please join our [codemagic slack community](https://join.slack.com/t/codemagicio/shared_invite/zt-pt7dolhc-5Ltsqfg7EfPPhMUPMDA0EA) to ask your support related questions.
