### ISSUE TITLE
publish release notes to App Store Connect and Google Play store - 1. does it requires .json or .txt is ok? 2. adjust App Store Connect with Testflight

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#432]
https://docs.codemagic.io/publishing-yaml/publish-release-notes/

1.
first paragraph leaves the impression that having .txt in repo is enough to publish release notes to Google Play and App Store Connect. I am not sure whether we require .json format in order to account for locale or we assign default locale. Looks like it is true for Google Play i.e. if .txt is present then en-US locale is used, but not for App Store Connect? 

2.
Let's use Testflight instead of App Store Connect to avoid confusion, since IIRC from discussions with @nevercode-kevin and @artemii-yanushevskyi we do not update App Store listing release notes "What's new" section, but only the Testflight part regarding "what's new" so testers know what to test. I realise App Store Connect is correct term, but in this case I fear it creates false assumption. In reality we only support TestFlight and not App Store. 

In general I think we could do a better job with this section of docs.

**Comment by fbartho** [comment]
Totally am interested if you consider a process for uploading release notes for the AppStoreConnect side of the equation too!

TestFlight notes should be separate from Store notes. We're not likely to localize our TestFlight notes, but definitely want to do so for our Store notes!

**Comment by icarusdust** [comment]
PR submitted to make updates in the docs accordingly after testing on our end.
