### ISSUE TITLE
Apple processing time

### ISSUE THREAD

**Issue by icarusdust** [codemagic-ci-cd/codemagic-docs#438]
Currently in the post-processing section when we get this error :"Did not find build matching uploaded version yet, it might be still processing. Waiting to try again...", it does not give any hint about what it is. And the docs also do not provide any info about it.  Maybe updating the docs and linking it in the logs would be a good idea.

**Comment by helinanever** [comment]
Post-processing has been described in a subsection of https://docs.codemagic.io/yaml-publishing/distribution/#app-store-connect.

**Comment by kemane-donfack** [comment]
hi i have the same problem how to solve it
