### ISSUE TITLE
Add steps to troubleshoot Flutter flavorizer iOS flavors code signing issues

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/codemagic-docs#443]
### CodeMagic fails to build iOS (when using Flutter Flavorizr Package) due to Code Signing Issues

If CodeMagic fails due to code-signing issues, it's probably because the Flutter iOS folder was originally created with an older version of Flutter, and then never re-created from scratch (while Flutter continued to upgrade).

To fix the issue - and assuming Flavorizr package is used - execute the following steps:
1. Backup your iOS icons folder as well as the Android icons folder
2. Delete the ./ios folder
3. Run "flutter create ."
4. Restore the icons into the ./ios and ./android folders
5. Run "flutter pub run flutter_flavorizr"
6. Make sure that the default Runner scheme has a valid bundle-identifier which matches an existing Identifier in developer.apple.com
7. Build locally and if successful - push to CodeMagic

##### Important Note
After running step 4, the main-{{env}} files will be wiped-out - and will need to be restored, so you must back them up first (or simply discard the changes to these files via Git after running flavorizr).

**Comment by nevercode-kevin** [comment]
Closing for now. Can be incorporated as a troubleshooting step when adding documentation about setting up and using flutter_flavorizr package.

**Comment by fixer112** [comment]
Still not fixed
