### ISSUE TITLE
Testing: docs are missing the command to wait for device when launching the emulator

### ISSUE THREAD

**Issue by helinanever** [codemagic-ci-cd/codemagic-docs#445]
Running Flutter integration tests from yaml fail because the build doesn't wait for the emulator to be launched.
Adding the `adb wait-for-device ` command fixes the issue.

```
- name: Launch emulator
  script: |
    flutter emulators --launch emulator
    adb wait-for-device 
```
The same command can be documented for other project types too.

**Comment by icarusdust** [comment]
I would assume that adding **adb wait-for-device** is not only Flutter integration test related but also for all the platforms and it should be added no only under Flutter section but somewhere here: https://docs.codemagic.io/yaml-testing/testing/

**Comment by icarusdust** [comment]
well, not actually because the other examples already include it, so it should be Flutter specific
