### ISSUE TITLE
Rest API: add all possible statuses to `GET /builds/:id` description

### ISSUE THREAD

**Issue by mikhail-tokarev** [codemagic-ci-cd/codemagic-docs#446]
users can't find information about all possible status values

**Comment by icarusdust** [comment]
This is the response of the API request:

{
  "application": {
    "_id": "5d85eaa0e941e00019e81bc2",
    "appName": "counter_flutter"
  },
  "build": {
    "_id": "5ec8eea2261f342603f4d0bc",
    "startedAt": "2020-05-23T09:36:39.028+0000",
    "status": "building",
    "workflowId": "5d85f242e941e00019e81bd2"
  }
}

It is already in the docs mentioned.

**Comment by icarusdust** [comment]
Added all the statuses as a list to the docs.
