### ISSUE TITLE
create more detailed documentation on how Google Tracks work

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/codemagic-docs#451]
Feedback from one of our users. He forgot he needed to upload first build manually to Google Play when setting up a new app. This would be a great docs improvement. :slightly_smiling_face:

> Hi Chris - I eventually got it to work. Your docs could call out how to deal with the Google Play Tracks more precisely. I did not fully understand all that (internal vs open vs closed testing) and I manually uploading to the internal track when I should have to the Alpha track. Maybe it's explained, but there are so many levers and switches that a step-by-step document for morons would be really helpful.

**Comment by icarusdust** [comment]
Either the docs have recently been updated or it is as is, it looks self explanatory to me about tracks. https://docs.codemagic.io/flutter-publishing/publishing-to-google-play/

**Comment by helinanever** [comment]
The tracks are explained in Flutter workflow editor docs but not in the yaml docs:
https://docs.codemagic.io/yaml-publishing/distribution/#google-play

**Comment by icarusdust** [comment]
Correct, going to submit a PR

**Comment by helinanever** [comment]
Fixed by https://github.com/codemagic-ci-cd/codemagic-docs/pull/463
