### ISSUE TITLE
upload credentials.json

### ISSUE THREAD

**Issue by nyck33** [codemagic-ci-cd/codemagic-docs#546]
https://docs.codemagic.io/flutter-publishing/publishing-to-google-play/

I am new to Flutter and have a paid Google Play developer account so now I have two consoles: Google Play Console and the other GCP console.  I am not sure if they are connected.  S.O. answers were not clear on how to get this credentials json I need to have CodeMagic do the CI CD thing for my Flutter app here:  https://codemagic.io/app/61496398b1c014cc2890f906/workflow/61496398b1c014cc2890f905/settings

Please walk us through step by step when the documentation from Google is not very clear on this step either.

**Comment by K-Codemagic** [comment]
We have updated the document on how to publish apps on google play. Let me know if you still face any issues.
https://docs.codemagic.io/flutter-publishing/publishing-to-google-play/
In case of any concerns, you can also get help in our Slack community - https://slack.codemagic.io/

**Comment by K-Codemagic** [comment]
Also, for JSON key, you can check all the steps on how to get the key: https://docs.codemagic.io/knowledge-base/google-services-authentication/#creating-a-service-account

**Comment by icarusdust** [comment]
You can also join our community slack channel for your questions or send your queries to nihal@nevercode.io
