### ISSUE TITLE
display logs for Timeouted builds

### ISSUE THREAD

**Issue by furaiev** [codemagic-ci-cd/codemagic-docs#552]
Currently, a user can't see a log in the Codemagic UI when the build has Timeout status.

Please display the log in the same way as for success/failed builds. It contains a lot of important information about Timeout reasons.

![image](https://user-images.githubusercontent.com/33546696/135456589-d73f6275-ab05-4043-a91d-e3cf1fe98c9d.png)

**Comment by icarusdust** [comment]
The issue has been fixed!! Logs are available.
