### ISSUE TITLE
Moving repo from personal GitHub to organisation account 

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#567]
Users have had issues with moving repositories from personal GitHub account to organisation account. 

e.g. https://codemagicio.slack.com/archives/CEKE2KZ37/p1634195217042100

> Hey guys!
> I’ve set up a private repository on Codemagic. I then transferred the repository to Organization, added the Codemagic app to Organization, and configured it. However, the transferred repository does not show up in the shared apps section. Instead, the repository before the transfer is shown. I assume this is because the previous information has not been updated. What should I do?
> I’ll share the app I set up before the transfer.
> https://codemagic.io/app/60f6f0440c5097715793bfbe/workflow/60f6f0440c5097715793bfbd/settings

would be great if we can reproduce and document this case in docs.

**Comment by icarusdust** [comment]
Codemagic CI/CD GitHub App  needs to be configured correctly, otherwise transferring a repo to an organisation will not show the repo. In short, an organisation should have Codemagic CI/CD GitHub App configured as well.
