### ISSUE TITLE
Flavor Workflow Ios Automatic code signing issue

### ISSUE THREAD

**Issue by fixer112** [codemagic-ci-cd/codemagic-docs#659]
Automatic signing works only for 2 workflow out of 5. The rest gives error such as == Building for iOS ==

> xcode-project use-profiles
Configure code signing settings
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /Users/builder/Library/codemagic-cli-tools/keychains/24-12-21_g5b4xu8j.keychain-db
Searching for files matching /Users/builder/clone/ios/**/*.xcodeproj
Completed configuring code signing settings
Did not find matching provisioning profiles for code signing!
Generated options for exporting the project
 - Method: ad-hoc
 - Provisioning Profiles: []
 - Signing Certificate: 
 - Signing Style: manual
 - Team Id: 
Saved export options to /Users/builder/export_options.plist

> flutter build ipa --release --export-options-plist /Users/builder/export_options.plist --flavor meculium -t lib/main-meculium.dart --build-name=1.0.2 --build-number=3
Archiving com.example.com...
Automatically signing iOS for device deployment using specified development team in Xcode project: Q2N9BPD86Q
Running pod install...                                              7.0s
Running Xcode build...                                          
Xcode archive done.                                          8.3s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:BDBAD2FC-16AD-45F2-8BA2-1B6A744CAFB6, OS:14.5, name:iPad (8th generation) }
    { platform:iOS Simulator, id:03A783D6-D52A-4FFF-B04F-6A692F09A948, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:5E28BE25-E070-45EB-AB47-12D439953F74, OS:15.2, name:iPad (9th generation) }
    { platform:iOS Simulator, id:AF693EA2-3CEE-406E-9FD3-2AEF7C7AE4E0, OS:14.5, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:F98892BC-3737-4027-AFD2-BBDF1C17ECBF, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:BF716E5F-06B8-44B6-AF79-A20FEE5CD454, OS:15.2, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:A9EBBABF-6741-4F1E-9139-E5713AF89F7E, OS:14.5, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:E8CE8886-0B2C-43FF-8EEE-603A8A1685C8, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:5CEE762F-674E-41AD-94DF-48B807120673, OS:15.2, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:CE50B412-8301-4439-86D9-218E9B520C64, OS:14.5, name:iPad Pro (11-inch) (2nd generation) }
    { platform:iOS Simulator, id:503ED4B8-9480-401C-99CC-F37B5E9DEDEE, OS:14.5, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:9FD9A6C7-96D1-427D-BBCA-DDE9DFA903BA, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:13E7B931-0FA1-4DF7-A3B3-35641D91EAF0, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:560D986F-3412-47DA-B037-69BBD7873E2B, OS:14.5, name:iPad Pro (12.9-inch) (4th generation) }
    { platform:iOS Simulator, id:99B14BF4-7966-4427-ACD1-34BFE4D26A01, OS:14.5, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:EF9AE2FD-212D-4D6C-AF22-73D7491B8B7F, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:915A71A8-21B4-43E0-B8A7-54D3C19D6CCC, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:9E2823A4-64EA-4D60-A7EF-B401D4EE9D47, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:062BC467-73D4-4667-A238-2207CDE338C1, OS:15.2, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:ED635705-38B8-41E4-977A-009F1893C7C8, OS:14.5, name:iPhone 8 }
    { platform:iOS Simulator, id:7C5473C2-9C4E-47E5-8282-442FDF8EB347, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:557184DB-BC86-4D96-B073-EE865DFAFF8C, OS:15.2, name:iPhone 8 }
    { platform:iOS Simulator, id:6689C1EF-3619-4DE3-AF9F-4A0BAB1FD532, OS:14.5, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:A634BCFD-FC7A-470C-889A-62808EDCE7B5, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:1328BA99-16C6-420C-AE3A-19B0C2BB0624, OS:15.2, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:A8F9CFAD-11FF-46A2-B957-11CB50A189EE, OS:14.5, name:iPhone 11 }
    { platform:iOS Simulator, id:9392FD28-3E15-4CD2-B4D1-BD5B48E6238D, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:A160C8D6-C529-4B7A-BB48-313FA2985D79, OS:15.2, name:iPhone 11 }
    { platform:iOS Simulator, id:1F17BDC6-F7BA-4D6C-AED3-19992BE39743, OS:14.5, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:1228C53F-AD8F-494F-A7C3-4D53005062DF, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:829BD982-3245-4167-A2FD-1B632EBD5508, OS:15.2, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:86ABCECA-0FF3-4244-925A-CEA93D003D6A, OS:14.5, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:C47A5DA4-03E4-415C-9B28-CFE17AD81A4F, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:B325B296-9152-4C08-B195-6EE994D2F828, OS:15.2, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:839F3C4C-B9BC-4F54-BF0F-84CE9BDF79E4, OS:14.5, name:iPhone 12 }
    { platform:iOS Simulator, id:243CD93E-F060-4413-936A-E1C717A78DBE, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:4A9059CF-E08D-44B2-AAD7-D65A7BBEF166, OS:15.2, name:iPhone 12 }
    { platform:iOS Simulator, id:4E0DDFA4-6C79-4774-9616-20514A2A8714, OS:14.5, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:D6C83C0B-6EF8-4866-B532-F4CF7ED69C50, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:D56DB4E9-00BB-461F-B67A-EE346087BB9F, OS:15.2, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:EE34ECEA-7277-410B-90B2-23DEC7C06077, OS:14.5, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:64FC4CC4-95DA-48FE-9980-8AB26CEE9892, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:D0F51A68-F863-40CD-80FD-E02290E66CFC, OS:15.2, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:DEF97C06-7FB2-4895-9B5D-11CA40EB3213, OS:14.5, name:iPhone 12 mini }
    { platform:iOS Simulator, id:E2866178-464C-4D5C-A13D-3597F07DD133, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:55880680-3683-47FC-958C-6631530A3721, OS:15.2, name:iPhone 12 mini }
    { platform:iOS Simulator, id:EF87D420-E8D1-4B12-B85C-4BBA52FBD220, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:4535E403-5294-4602-BFD4-B1C957296A36, OS:15.2, name:iPhone 13 }
    { platform:iOS Simulator, id:AC52617F-729B-4308-8CDB-FD850720B274, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:DF3FDAAB-5131-45A6-A5AC-701786499EFF, OS:15.2, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:25315873-BCF7-4159-B6E1-5BD7A2533650, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:E6286BC6-2669-4301-BC80-EC5EF5492B91, OS:15.2, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:2D48F1AA-93AC-48DA-99E7-1B1D44ED5E66, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:3DE7AA51-BDF2-409A-997E-A58DBFD669C9, OS:15.2, name:iPhone 13 mini }
    { platform:iOS Simulator, id:EA386A2D-32C2-4593-B2B9-2182F366C195, OS:14.5, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:B47CBB9A-B743-4983-AE42-D576BFB99930, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:8915C15C-81AF-4B5F-BA78-2FC47CE77614, OS:15.2, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:14C619EC-2882-497C-A2A9-6130E2D2BF8C, OS:14.5, name:iPod touch (7th generation) }
    { platform:iOS Simulator, id:4F9DD40E-EB0B-4C05-876A-8E1FFC9BAEF8, OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS Simulator, id:B3EFCA68-DC2C-4B85-BBCD-13153CE2ECCE, OS:15.2, name:iPod touch (7th generation) }
    ** ARCHIVE FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    error: No profiles for 'com.example.com' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.com'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')

Encountered error while archiving for device.

Build failed :|
Failed to build for iOS

**Comment by icarusdust** [comment]
Hey, seems like your provisioning profile comes empty and the issue occurs from that step on. We need to figure out why it is empty. Please post your query in our community slack channel or your can direct it to nihal@nevercode.io directly.
