### ISSUE TITLE
Android code signing should not recommend adding credentials to build.gradle

### ISSUE THREAD

**Issue by nevercode-kevin** [codemagic-ci-cd/codemagic-docs#685]
https://docs.codemagic.io/yaml-code-signing/signing-android/#signing-android-apps-using-gradle

This suggests that it's ok to put your keystore credentials in the build.gradle for local builds. You should either add the credentials on your local machine or use a properties file that is not checked into source control.

**Comment by Ismoh** [comment]
Doesn't it say to decode the credentials and use variables set in codemagics user settings?

> 2. Save the keystore file, keystore password (if keystore is password-protected), key alias and key alias password (if key alias is password-protected) to the respective environment variables in the Environment variables section in Codemagic UI. Click Secure to encrypt the values. Note that binary files (i.e. keystore) have to be [base64 encoded](https://docs.codemagic.io/variables/environment-variable-groups/#storing-sensitive-valuesfiles) locally before they can be saved to environment variables and decoded during the build.

**Comment by K-Codemagic** [comment]
The changes have been made! Closing this!
