### ISSUE TITLE
Permissions required for service accounts in GCP for publishing to Google Play

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-docs#722]
We may not require all the permissions that editor role provides when creating a service account in order to publish to Google Play Store. Ref: https://docs.codemagic.io/knowledge-base/google-services-authentication/#creating-a-service-account

Let's investigate it and try to reduce the amount of permissions we recommend giving if possible

**Comment by VeArnold** [comment]
Fixed in https://github.com/codemagic-ci-cd/codemagic-docs/pull/724
