### ISSUE TITLE
Badge styling

### ISSUE THREAD

**Issue by Ismoh** [codemagic-ci-cd/codemagic-docs#766]
Is it possible to change the style of the build status badge?
I wasnt able to find anything while researching.
Thanks!

**Comment by Ismoh** [comment]
Well, no styling then :D

**Comment by icarusdust** [comment]
@Ismoh I guess I did not catch the root of the question :)) So, you would like to customise style of a badge status. Correct ? Seems like it is not possible  at the moment but we could add it as a feature. I just need to get the idea of how exactly you would like to re-style it and if there is any particular reason for that ?

**Comment by Ismoh** [comment]
It is just for aesthetic.
I already created an issue on shields.io to add your service to their crawling API.
Badgen.net is also a provider for customized badges, but for build status and similiar there has to be an API. You can add static badges, but there is no reason for static build badges.

https://github.com/badges/shields/issues/5790

This is an example for badges with a different style:
https://github.com/Ismoh/NoitaMP
