### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by pratik-bit** [codemagic-ci-cd/codemagic-docs#84]
import 'package:flutter/material.dart';

class Cart_products extends StatefulWidget {
  @override
  _Cart_productsState createState() => _Cart_productsState();
}

class _Cart_productsState extends State<Cart_products> {
  var Products_on_cart = [
    {
     "name": "Blazer",
     "picture":"images/products/blazer1.png",
     "prise":50,
     "size":"M",
     "color":"Black",
     "quantity":1,

   },
   {
     "name": "Pink Dress",
     "picture":"images/products/dress1.png",
     "prise":85,
     "size":"M",
     "color":"pink",
     "quantity":1,
   },
  ];
  @override
  Widget build(BuildContext context) {
    return new ListView.builder(
      itemCount: 2,
      itemBuilder: (context, index)
      {
        return Singal_cart_product(
          cart_prod_name: Products_on_cart[index]["name"],
          cart_prod_picture: Products_on_cart[index]["picture"],
          cart_prod_prise: Products_on_cart[index]["prise"],
          cart_prod_color: Products_on_cart[index]["color"],
          cart_prod_size: Products_on_cart[index]["size"],
          cart_prod_qty: Products_on_cart[index]["quantity"],
        );
      });
   }
}

class Singal_cart_product extends StatelessWidget {
final cart_prod_name;
final cart_prod_picture;
final cart_prod_prise;
final cart_prod_size;
final cart_prod_color;
final cart_prod_qty;

Singal_cart_product({
  this.cart_prod_name,
  this.cart_prod_picture,
  this.cart_prod_prise,
  this.cart_prod_size,
  this.cart_prod_color,
  this.cart_prod_qty,
}
  );
  @override
  Widget build(BuildContext context) {
    return Card(
      child: ListTile(
        //Leading Section//
        leading: new Image.asset(
          cart_prod_picture,
           width:80.0,height:80.0
           ),
           //title Section//
        title:new Text(cart_prod_name),
        //subtitle Section//
         subtitle: new Column(
           children: <Widget>[
           //Row Inside The Column //
            new Row(
              children: <Widget>[
                Padding(padding: const EdgeInsets.all(0.0),
                child: new Text("Size:"),
                ),
                Padding(padding: const EdgeInsets.all(0.0),
                child: new Text(cart_prod_size, style: TextStyle(color: Colors.pinkAccent),),
                ),
                new Padding(padding: const EdgeInsets.fromLTRB(16.0, 4.0, 4.0, 0.0),
                child: new Text("Color:"),
                ),
                Padding(padding: const EdgeInsets.all(1.0),
                child: new Text(cart_prod_color, style: TextStyle(color:Colors.pinkAccent),),
                ),

              ],
            ),
            //this section is product prise//
            new Container(
              alignment: Alignment.topLeft,
              child: new Text("\$$cart_prod_prise",style: TextStyle(fontSize:17.0,
              fontWeight: FontWeight.bold,
              color: Colors.redAccent,
              ),
              ),
            ),
             ],
         ),
         trailing: new Column(
           children:<Widget>[
           IconButton(icon: Icon(Icons.arrow_drop_up), onPressed: (){}),
         
                    IconButton(icon: Icon(Icons.arrow_drop_down),onPressed: (){},)
                        
           ]
         )  
          ),
      
    );
  }
}

**Comment by pratik-bit** [comment]
A RenderFlex overflowed by 40 pixels on the bottom.

**Comment by rimanteval** [comment]
This issue is not related to Codemagic documentation in any way, therefore we'll close it :)
