### ISSUE TITLE
Dependency caching docs missing cache limits info

### ISSUE THREAD

**Issue by vbuberen** [codemagic-ci-cd/codemagic-docs#879]
While checking out the documentation on dependency caching https://docs.codemagic.io/flutter-configuration/dependency-caching/ but couldn't find information on how long cache lives, its limits, etc. This is useful info for quite a lot of people as it seems to me.

Would be good to have something, like, for example, Github's docs with such info about their Cache action: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

**Comment by icarusdust** [comment]
Info added, closing the issue.
