### ISSUE TITLE
Command to boot up emulator is not always working

### ISSUE THREAD

**Issue by remonh87** [codemagic-ci-cd/codemagic-docs#935]
At https://docs.codemagic.io/yaml-testing/testing/ you mention that to boot the android emulator for a Flutter app you can run `flutter emulators --launch emulator` this does not work in the Linux environment (you get 
No emulator found that matches 'Emulator' error) and I think it is better to change to change the command to:  `emulator @emulator` which will found and boot the emulator.

**Comment by icarusdust** [comment]
Hi @remonh87 thanks for the suggestion. I'll check it on my end and it to the docs. Closing the thread here.
