### ISSUE TITLE
Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`

### ISSUE THREAD

**Issue by mikhail-tokarev** [codemagic-ci-cd/codemagic-docs#956]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **tyler-jewell** September 15, 2022</sup>
While publishing to firebase hosting using the FIREBASE_TOKEN environment variable, I got this warning:

Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started

Can we update the documentation to reflect this?</div>

**Comment by icarusdust** [comment]
As Firebase docs still mention --token in their docs for authentication, I'll leave it as is.

**Comment by kevin-suhajda** [comment]
Both methods (Authenticating via service account and Authenticating via token) are in the documentation. There is also a warning note in the docs to say that using a token will be deprecated at some point in the future.

https://docs.codemagic.io/yaml-publishing/firebase-app-distribution/
