### ISSUE TITLE
Can't run the build with specify xcode 14.0

### ISSUE THREAD

**Issue by huynguyennang-fruitstreet** [codemagic-ci-cd/codemagic-docs#962]
Hi all.
- Currently, I using `xcode: latest` (Xcode 13.4.1) -> I build success
- But when I using `xcode: 14.0` -> I got issue: `Step 10 script Build ipa for distribution exited with status code 65`

![190973326-f6a20c61-1020-4f30-b20c-645a0171daa5](https://user-images.githubusercontent.com/87348098/192921616-2292713e-abda-4206-967b-59fa82c5a040.png)

Do you have any idea how to fix this error?

**Comment by icarusdust** [comment]
Hi, hard to say without checking the logs. Please provide a build is.

**Comment by huynguyennang-fruitstreet** [comment]
@icarusdust ica I using [youtube-ios-player-helper](https://github.com/youtube/youtube-ios-player-helper), this library is automatically signed for development, so I config `--archive-xcargs CODE_SIGN_STYLE=Manual` to fixed it. I will close issue now.
