### ISSUE TITLE
Incomplete Firebase Crashlytics dSYMs upload

### ISSUE THREAD

**Issue by nguyenthanhphap1413** [codemagic-ci-cd/codemagic-docs#978]
I tried to follow the documentation but it was uploaded incompletely. It just uploaded grpc.

```
echo "Find build artifacts"
dsymPath=$(find ~/build.xcarchive -name "*.dSYM.zip" | head -1)
if [[ -z ${dsymPath} ]]
then
  echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
else
  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
  ls -d -- ios/Pods/*
  $FCI_BUILD_DIR/ios/Pods/Crashlytics/iOS/Crashlytics.framework/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
fi
```
![Uploading Screen Shot 2022-09-24 at 21.36.31.png…]()

**Comment by icarusdust** [comment]
Hi, can you see the upload process in the logs ? Your attached image cannot be opened. Better send me a build id as well. In general, if you have multiple dSYM files, then you can make some changes in the script. Let me see if I can make it send it over.

**Comment by icarusdust** [comment]
Try something like this:

```
echo "List all dSYM files artifacts"
  find . -name "*.dSYM*"

  dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
  echo $dSymZipPath

  dSymPath="$(dirname "${dSymZipPath}")"
  ls $dSymPath

  repoPathToIosFolder="ios"

  googleServicesPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Runner/GoogleService-Info-Staging.plist"
  ls $googleServicesPath
 
  crashlyticsScriptPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Pods/FirebaseCrashlytics/upload-symbols"
  ls $crashlyticsScriptPath

  echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
  $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath
```

**Comment by nguyenthanhphap1413** [comment]
> Try something like this:
> 
> ```
> echo "List all dSYM files artifacts"
>   find . -name "*.dSYM*"
> 
>   dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
>   echo $dSymZipPath
> 
>   dSymPath="$(dirname "${dSymZipPath}")"
>   ls $dSymPath
> 
>   repoPathToIosFolder="ios"
> 
>   googleServicesPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Runner/GoogleService-Info-Staging.plist"
>   ls $googleServicesPath
>  
>   crashlyticsScriptPath="$FCI_BUILD_DIR/$repoPathToIosFolder/Pods/FirebaseCrashlytics/upload-symbols"
>   ls $crashlyticsScriptPath
> 
>   echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
>   $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath
> ```

It was not working, I resolved this by removing `| head -1`. It worked for me. because `| head -1` only submits the first dSYMs on the folder.

**Comment by icarusdust** [comment]
Glad that it worked. Closing the thread here. If any further questions, please raise it in Discussions.
