### ISSUE TITLE
Skipping build for Windows because C:\Users\builder\clone\windows runner does not exist.

### ISSUE THREAD

**Issue by markhorrocks** [codemagic-ci-cd/codemagic-docs#989]
### Discussed in https://github.com/orgs/codemagic-ci-cd/discussions/988

<div type='discussions-op-text'>

<sup>Originally posted by **markhorrocks** September 28, 2022</sup>
I am trying to build a flutter app for Windows but it fails with `Skipping build for Windows because C:\Users\builder\clone\windows runner does not exist.`. 

I have developed the app in ubuntu and connected it to codemagic with the Github repo for the project.</div>

**Comment by himesh-cm** [comment]
It's being discussed here - https://github.com/orgs/codemagic-ci-cd/discussions/988

**Comment by himesh-cm** [comment]
solution - https://github.com/orgs/codemagic-ci-cd/discussions/988#discussioncomment-3750659
